create table TB_CONFIG_USUARIO(
ID_CONFIG_USUARIO INT NOT NULL auto_increment PRIMARY KEY,
FL_DARK_MODE BOOL NOT NULL DEFAULT FALSE,
FOREIGN KEY(ID_CONFIG_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
)ENGINE=InnoDB; 