CREATE TABLE TB_GRUPO_PERMISSAO(
ID_GRUPO_PERMISSAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_GRUPO INT NOT NULL,
ID_PERMISSAO INT NOT NULL,
FOREIGN KEY(ID_GRUPO) REFERENCES TB_GRUPO(ID_GRUPO),
FOREIGN KEY(ID_PERMISSAO) REFERENCES TB_PERMISSAO(ID_PERMISSAO)
);