CREATE TABLE TB_GRUPO(
ID_GRUPO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DS_GRUPO VARCHAR(100) NOT NULL,
DS_DESCRICAO VARCHAR(200),
FL_ADMIN BOOL NOT NULL DEFAULT 0
);


INSERT INTO TB_GRUPO VALUES(NULL, 'Admin', 'Pode administrar e acessar todas as funções', true)