CREATE TABLE TB_GRUPO_USUARIO(
ID_GRUPO_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_GRUPO INT NOT NULL,
ID_USUARIO INT NOT NULL,
FOREIGN KEY(ID_GRUPO) REFERENCES TB_GRUPO(ID_GRUPO),
FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

