CREATE TABLE `TB_USUARIO` (
  `ID_USUARIO` int NOT NULL AUTO_INCREMENT,
  `DS_NOME` varchar(100) NOT NULL,
  `DT_NASCIMENTO` datetime NOT NULL,
  `DS_LOGIN` varchar(30) NOT NULL,
  `DS_SENHA` varchar(30) NOT NULL,
  `DS_EMAIL` varchar(100) NOT NULL,
  `FL_ATIVO` tinyint(1) NOT NULL DEFAULT '0',
  `DT_ULTIMO_ACESSO` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

