CREATE TABLE IF NOT EXISTS tb_campanha(
ID_CAMPANHA INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
DS_NOME_CAMPANHA VARCHAR(100) NOT NULL,
DS_LORE TEXT,
DT_CRIACAO DATETIME NOT NULL,
FL_ATIVO BOOL NOT NULL,
FL_PUBLICA BOOL NOT NULL,
DS_FOTO TEXT,
ID_USUARIO_CRIADOR INT NOT NULL,
ID_MESTRE_CAMPANHA INT NOT NULL,
FOREIGN KEY(ID_USUARIO_CRIADOR) REFERENCES tb_usuario(ID_USUARIO),
FOREIGN KEY(ID_MESTRE_CAMPANHA) REFERENCES tb_usuario(ID_USUARIO)
)ENGINE=InnoDB;
