CREATE TABLE IF NOT EXISTS tb_campo_ficha(
ID_CAMPO_FICHA INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
DS_NOME_CAMPO VARCHAR(50) NOT NULL,
NR_TIPO_CAMPO INT NOT NULL,
DS_REFERENCIA VARCHAR(30),
DS_DESCRICAO TEXT,
FL_TEM_MODIFICADOR BOOL NOT NULL,
FL_BLOQUEADO BOOL,
FL_VISIVEL BOOL,
DS_FORMULA_MODIFICADOR VARCHAR(50),
DS_VALOR_PADRAO TEXT,
NR_ORDEM INT NOT NULL,
FL_ATIVO BOOL NOT NULL,
ID_CAMPANHA INT NOT NULL,
FOREIGN KEY(ID_CAMPANHA) REFERENCES tb_campanha(ID_CAMPANHA)
)ENGINE=InnoDB;


