CREATE TABLE IF NOT EXISTS tb_chat(
ID_CHAT INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_USUARIO_1 INT NOT NULL,
ID_USUARIO_2 INT NOT NULL,
FL_ATIVO_USR_1 BOOL NOT NULL,
FL_ATIVO_USR_2 BOOL NOT NULL,
FOREIGN KEY(ID_USUARIO_1) REFERENCES tb_usuario(ID_USUARIO),
FOREIGN KEY(ID_USUARIO_2) REFERENCES tb_usuario(ID_USUARIO)
)ENGINE=InnoDB;
