CREATE TABLE IF NOT EXISTS tb_dados_ficha(
ID_DADO_FICHA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_CAMPO_FICHA INT NOT NULL,
ID_PERSONAGEM INT NOT NULL,
DS_VALOR TEXT,
FOREIGN KEY(ID_CAMPO_FICHA) REFERENCES tb_campo_ficha(ID_CAMPO_FICHA),
FOREIGN KEY(ID_PERSONAGEM) REFERENCES tb_personagem(ID_PERSONAGEM)
)ENGINE=InnoDB;
