CREATE TABLE IF NOT EXISTS tb_ficha(
ID_FICHA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DS_TENDENCIA VARCHAR(30),
DS_SOBRE TEXT,
NR_XP INT NOT NULL,
NR_MAX_PV INT NOT NULL,
NR_MAX_PM INT NOT NULL,
NR_PV INT NOT NULL,
NR_PM INT NOT NULL,
NR_PONTOS_HAB INT NOT NULL,
NR_STR INT,
NR_DEX INT,
NR_CON INT,
NR_INT INT,
NR_WIS INT,
NR_CHA INT,
ID_RACA INT,
ID_CLASSE INT,
ID_PERSONAGEM INT NOT NULL,
ID_CAMPANHA INT NOT NULL,
FOREIGN KEY(ID_RACA) REFERENCES tb_raca(ID_RACA),
FOREIGN KEY(ID_CLASSE) REFERENCES tb_classe(ID_CLASSE),
FOREIGN KEY(ID_PERSONAGEM) REFERENCES tb_personagem(ID_PERSONAGEM),
FOREIGN KEY(ID_CAMPANHA) REFERENCES tb_campanha(ID_CAMPANHA)
)ENGINE=InnoDB;


