CREATE TABLE IF NOT EXISTS tb_ficha(
ID_FICHA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_CAMPO_FICHA INT NOT NULL,
ID_PERSONAGEM INT NOT NULL,
ID_USUARIO INT NOT NULL,
DS_VALOR TEXT,
FOREIGN KEY(ID_CAMPO_FICHA) REFERENCES tb_campo_ficha(ID_CAMPO_FICHA),
FOREIGN KEY(ID_PERSONAGEM) REFERENCES tb_personagem(ID_PERSONAGEM),
FOREIGN KEY(ID_USUARIO) REFERENCES tb_usuario(ID_USUARIO)
)ENGINE=InnoDB;